name: Publish to PyPI
on:
  push:
    branches:
      - github_actions

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Update Version
        env:
          NEW_VERSION: 2.3.3  # Replace '1.2.3' with your desired version
        run: |
          sed -i "s/^VERSION = .*/VERSION = '${NEW_VERSION}'/" setup.py
      - name: Build and Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository pypi dist/* 
