name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ secrets.NEW_VERSION }} # You can set a default version using a secret or a fixed value.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Modify the 'env.list' file with the desired version
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=${VERSION}" >> env.list
        shell: bash

      - name: Update version in setup.py
        env:
          VERSION: ${{ env.VERSION }} # Accessing the VERSION environment variable
        run: |
          sed -i "s/version=\"[0-9.]*\"/version=\"$VERSION\"/" setup.py

      - name: Install dependencies
        run: pip install setuptools wheel twine

      - name: Build and Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
