name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Define an environment variable 'VERSION' and set it to the desired version manually
      - name: Set VERSION environment variable
        run: |
          echo "Enter the new version (in format X.Y.Z):"
          echo "::set-env name=VERSION::$(read -r version && echo $version)"

      - name: Update version in setup.py
        env:
          VERSION: ${{ env.VERSION }} # Accessing the VERSION environment variable
        run: |
          sed -i "s/version=\"[0-9.]*\"/version=\"$VERSION\"/" setup.py

      - name: Install dependencies
        run: pip install setuptools wheel twine

      - name: Build and Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
